# Generated by Django 4.2.7 on 2026-01-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='user_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
