# Generated by Django 4.2.7 on 2026-01-11 20:43

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WebhookEndpoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("merchant_id", models.UUIDField(db_index=True)),
                ("url", models.URLField()),
                ("secret", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("events", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "webhook_endpoints",
            },
        ),
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("endpoint_id", models.UUIDField(db_index=True)),
                ("merchant_id", models.UUIDField(db_index=True)),
                ("event_type", models.CharField(max_length=50)),
                ("payload", models.JSONField()),
                ("signature", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("retrying", "Retrying"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("response_code", models.IntegerField(blank=True, null=True)),
                ("response_body", models.TextField(blank=True, null=True)),
                ("retry_count", models.IntegerField(default=0)),
                ("max_retries", models.IntegerField(default=3)),
                ("next_retry_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "webhook_deliveries",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["endpoint_id", "status"],
                        name="webhook_del_endpoin_4ffb63_idx",
                    ),
                    models.Index(
                        fields=["merchant_id", "status"],
                        name="webhook_del_merchan_bbc37a_idx",
                    ),
                ],
            },
        ),
    ]
