# Generated by Django 4.2.7 on 2026-01-11 20:43

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ledger",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("entity", models.CharField(db_index=True, max_length=50)),
                ("entity_id", models.UUIDField(db_index=True)),
                (
                    "credit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "debit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("balance", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "reference_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("reference_id", models.UUIDField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "ledgers",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["entity", "entity_id"], name="ledgers_entity_9732e0_idx"
                    )
                ],
            },
        ),
    ]
