# Generated by Django 4.2.7 on 2026-01-12 08:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantPaymentConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('config_type', models.CharField(choices=[('bank_account', 'Bank Account'), ('upi', 'UPI'), ('razorpay', 'Razorpay'), ('stripe', 'Stripe'), ('phonepe', 'PhonePe'), ('paytm', 'Paytm'), ('other', 'Other')], max_length=50)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('account_holder_name', models.CharField(blank=True, max_length=255, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=11, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=255, null=True)),
                ('upi_id', models.CharField(blank=True, max_length=255, null=True)),
                ('provider_key', models.CharField(blank=True, max_length=255, null=True)),
                ('provider_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('provider_merchant_id', models.CharField(blank=True, max_length=255, null=True)),
                ('provider_webhook_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_configs', to='merchants.merchant')),
            ],
            options={
                'db_table': 'merchant_payment_configs',
                'ordering': ['-is_primary', '-created_at'],
                'indexes': [models.Index(fields=['merchant', 'config_type'], name='merchant_pa_merchan_889200_idx'), models.Index(fields=['merchant', 'is_primary'], name='merchant_pa_merchan_3a9e33_idx')],
            },
        ),
    ]
