# Generated by Django 4.2.7 on 2026-01-12 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('merchants', '0002_merchantpaymentconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantpaymentconfig',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='Admin user who verified this payment configuration', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payment_configs', to=settings.AUTH_USER_MODEL),
        ),
    ]
