# Generated by Django 4.2.7 on 2026-01-12 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            # Convert user_id from integer to UUID
            sql=[
                # First, drop ALL foreign key constraints on user_id
                "DO $$ DECLARE r RECORD; BEGIN FOR r IN (SELECT conname FROM pg_constraint WHERE conrelid = 'django_admin_log'::regclass AND contype = 'f' AND conname LIKE '%user_id%') LOOP EXECUTE 'ALTER TABLE django_admin_log DROP CONSTRAINT IF EXISTS ' || quote_ident(r.conname); END LOOP; END $$;",
                # Set user_id to NULL temporarily (since we can't convert integer to UUID directly)
                "UPDATE django_admin_log SET user_id = NULL WHERE user_id IS NOT NULL;",
                # Convert the column to UUID (nullable)
                "ALTER TABLE django_admin_log ALTER COLUMN user_id DROP NOT NULL;",
                "ALTER TABLE django_admin_log ALTER COLUMN user_id TYPE uuid USING NULL;",
                # Re-add the foreign key constraint pointing to users table
                "ALTER TABLE django_admin_log ADD CONSTRAINT django_admin_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL;",
            ],
            reverse_sql=[
                # Reverse: convert back to integer (this will lose data, so be careful)
                "ALTER TABLE django_admin_log DROP CONSTRAINT IF EXISTS django_admin_log_user_id_fkey;",
                "ALTER TABLE django_admin_log ALTER COLUMN user_id TYPE integer USING NULL;",
            ],
        ),
    ]
