# Generated by Django 4.2.7 on 2026-01-11 20:43

from decimal import Decimal
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.UUIDField(db_index=True)),
                ("merchant_id", models.UUIDField(db_index=True)),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=20
                    ),
                ),
                ("currency", models.CharField(default="INR", max_length=3)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "wallets",
                "indexes": [
                    models.Index(
                        fields=["user_id", "merchant_id"],
                        name="wallets_user_id_472a67_idx",
                    )
                ],
                "unique_together": {("user_id", "merchant_id")},
            },
        ),
    ]
