# Generated by Django 4.2.7 on 2026-01-11 20:43

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CryptoTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("payment_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("merchant_id", models.UUIDField(db_index=True)),
                (
                    "tx_hash",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("from_address", models.CharField(max_length=255)),
                ("to_address", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=18, max_digits=30)),
                ("network", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("block_number", models.BigIntegerField(blank=True, null=True)),
                ("confirmations", models.IntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "crypto_transactions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tx_hash"], name="crypto_tran_tx_hash_eb92f3_idx"
                    ),
                    models.Index(
                        fields=["payment_id", "status"],
                        name="crypto_tran_payment_b223b3_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CryptoAddress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.UUIDField(db_index=True)),
                ("merchant_id", models.UUIDField(db_index=True)),
                ("address", models.CharField(db_index=True, max_length=255)),
                (
                    "network",
                    models.CharField(
                        choices=[
                            ("ethereum", "Ethereum"),
                            ("polygon", "Polygon"),
                            ("bsc", "Binance Smart Chain"),
                        ],
                        default="ethereum",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "crypto_addresses",
                "unique_together": {("user_id", "merchant_id", "network")},
            },
        ),
    ]
