# Generated by Django 4.2.7 on 2026-01-11 20:43

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Token",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.UUIDField(db_index=True)),
                ("merchant_id", models.UUIDField(db_index=True)),
                ("token_hash", models.CharField(db_index=True, max_length=255)),
                ("encrypted_token", models.TextField()),
                (
                    "token_type",
                    models.CharField(
                        choices=[
                            ("card", "Card"),
                            ("bank_account", "Bank Account"),
                            ("upi", "UPI"),
                        ],
                        max_length=20,
                    ),
                ),
                ("last_four", models.CharField(blank=True, max_length=4, null=True)),
                ("expiry_month", models.IntegerField(blank=True, null=True)),
                ("expiry_year", models.IntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "tokens",
                "indexes": [
                    models.Index(
                        fields=["user_id", "merchant_id"],
                        name="tokens_user_id_394b0f_idx",
                    )
                ],
            },
        ),
    ]
